### ISSUE TITLE
HTML Report: link to source file should not be absolute

### ISSUE THREAD

**Issue by jmini** [selesse/jxlint#10]
In the HTML Report, there is an absolute link to the corresponding file:
![screenshot_report](https://cloud.githubusercontent.com/assets/1222165/26579032/84968d42-4532-11e7-9c35-b252feb489ac.png)

This doesn’t work well on windows, because the link point to `C:\***\git\jxlint-experiments\example-project-java\src\test\java\fr\jmini\java\example\JavaExampleTest.java`

The complete corresponding snippets look like this:

    <div class="panel-heading">
        <h4>
            <span class="label label-danger">ERROR</span>
            <a href="#functionsstartingwithtestaretests">Functions starting with 'test' are tests</a> violated in <a href="C:\***\git\jxlint-experiments\example-project-java\src\test\java\fr\jmini\java\example\JavaExampleTest.java">src/test/java/fr/jmini/java/example/JavaExampleTest.java</a> on line 15
        </h4>
    </div>

In my opinion usage of `$lintError.file` on [Line 116 of report.vm](https://github.com/selesse/jxlint/blob/master/jxlint/src/main/resources/velocity/report.vm#L116) is not good enough.

First I was thinking that we would need the path relative to the html-report output location `options.getOption(JxlintOption.OUTPUT_TYPE_PATH)`. I now think that it would be better to split the path in two parts: `$SourceFolderPathPrefix` + `$TemplateHelper.relativize($lintError.file)`

If not set, the initial value for `SourceFolderPathPrefix` could be (pseudo-code):

`SourceFolderPathPrefix = FileUtils.getRelativePath(options.getOption(JxlintOption.OUTPUT_TYPE_PATH), LintRulesImpl.getInstance().getSourceDirectory())`

This provides the possibility to set something like `https://github.com/me/myproject/blob/master/` and then you get something that link to the location of your source code. This is useful, if you only keep the `report.html` as archived artifact of a continuous build. The user will get a link to the online code viewer.

What do you think?

I will be happy to work on a pull request if you agree with this idea and if you provide some pointers on how to solve this... Let me know.

**Comment by selesse** [comment]
Thanks for reaching out!

I'd never been comfortable with the implementation of the absolute path. Just for context: at the time, my rationale was that the report's links should continue to resolve independently of where the report is on the file system.

I like your idea of the `SourceFolderPathPrefix`. If you don't move the report, it works. If you want absolute paths, you can provide it as the prefix. I really also like the idea of the report being able to be used from a CI context - even [my own sample report](http://selesse.com/jxlint/sample-report/index.html) has busted absolute paths.

I'm happy with your ideas and would definitely approve the PR based on your proposal. Let me know if you need anything from me. :)

**Comment by jmini** [comment]
Thank you for your quick reaction. I am happy that this proposal got accepted.

For your example on the CI Server, the new value should be set to something like: 
`https://github.com/selesse/jxlint/blob/master/jxlint-impl/src/`

I am not sure when I will be able to start to work on this. I will keep you informed.

**Comment by jmini** [comment]
It would be great to have this for the 2.0 version of jxlint.
