### ISSUE TITLE
Install a SNAPSHOT version in the local maven repository with gradle

### ISSUE THREAD

**Issue by jmini** [selesse/jxlint#14]
_(I am really new to gradle)_.
I would like to build the jxlint framework with gradle and to do something equivalent to `mvn install` in order to be able to consume the compiled code as maven artifact from other local maven projects.

As far as I understand it, there is a `publishToMavenLocal` task, but I did not managed to trigger it.
https://docs.gradle.org/3.3/userguide/publishing_maven.html

I have the feeling that this task should be configured/registered somehow. If no additional configuration is requested, maybe some documentation could be added somewhere.

**Comment by selesse** [comment]
You can achieve this by running `./gradlew install`.

**Comment by jmini** [comment]
Thank you very much for this answer. 

I got a the jar in my local maven repo: `com/selesse/jxlint/2.0.0-SNAPSHOT/jxlint-2.0.0-SNAPSHOT.jar`
