### ISSUE TITLE
Extend the Dispatcher in order to use it in other contexts

### ISSUE THREAD

**Issue by jmini** [selesse/jxlint#15]
I am working on #12. I think that the `Dispatcher` class could be improved. 

---

The first problem is the line `ProgramExitter.exitProgramWithMessage(message, ExitType.COMMAND_LINE_ERROR)`
When the dispatcher is called in a maven context, you want to throw a `MojoExecutionException` (that is not a `RuntimeException` and needs to be declared in the method).

Have you an idea how you want to solve this?
1. Add a `throws Exception` on the `dispatch()` method and add method parameter to handle what do on error cases (a lambda that takes an the error message as String argument and do something depending on the context)

2. Add a `throws Exception` on `dispatch()` and make the `Dispatcher` class abstract. This way we can have a `CliDispacher` and a `MojoDispacher`.

The `throws Exception` pattern is not that nice, a new typed exception could be introduced `ConfigurationNotValidException` or something like that. Depending on the context, this Exception can be catched an mapped to the appropriate behavior (`ProgramExitter` or `MojoExecutionException`)

---

The second Problem I have: the way some of the configuration are stored in `ProgramOptions`. In particular the list of rules or of categories; I have lists of strings (derived by maven from the configuration) and I concatenate them into coma separated value in order to match the input from the cli tool.

---

I am not sure how this can evolve and I could profit from the ideas you have.

My approach for the moment, I do the checks in my mojo. This way I do not expect the `Dispatcher` to call `ProgramExitter.exitProgramWithMessage(..)`. This works but the verification are done twice.

**Comment by jmini** [comment]
I have a bigger problem for the moment:
I was working with the `1.7.2` version and when I have tried to update to `2.0.0` I have noticed that the constructor in Dispatcher is no longer `public`. The same goes for the `dispatch()` method.

What is the idea behind this change?

**Comment by selesse** [comment]
> the constructor in Dispatcher is no longer public. The same goes for the dispatch() method. [...] What is the idea behind this change?

The visibility wasn't necessary. It can be brought back if it's needed. Alternatively, the class that needs to construct it directly/call the method can be placed in the `com.selesse.jxlint` package.

**Comment by selesse** [comment]
> The first problem is the line ProgramExitter.exitProgramWithMessage(message, ExitType.COMMAND_LINE_ERROR)

> The throws Exception pattern is not that nice, a new typed exception could be introduced ConfigurationNotValidException or something like that. Depending on the context, this Exception can be catched an mapped to the appropriate behavior (ProgramExitter or MojoExecutionException)

I like the idea of throwing an exception and having logic to map to the appropriate behavior. Ideally, I'd like to keep the `MojoExecutionException` concern OUTSIDE of the jxlint project (and entirely inside `jxlint-maven`). I see you've already done that in #16.

**Comment by selesse** [comment]
> The second Problem I have: the way some of the configuration are stored in ProgramOptions. In particular the list of rules or of categories; I have lists of strings (derived by maven from the configuration) and I concatenate them into coma separated value in order to match the input from the cli tool.

I think any "wrapper" tool (i.e. Maven plugin, Gradle plugin, whatever) would have to convert their input into a `ProgramOptions, like you've done in `AbstractJxlintMojo#createProgramOptions`. Is this still a problem? What you've done looks good to me.

**Comment by jmini** [comment]
> The visibility wasn't necessary. It can be brought back if it's needed. Alternatively, the class that needs to construct it directly/call the method can be placed in the `com.selesse.jxlint` package.

With Java 9 and jigsaw, this is no longer allowed. When the module `jxlint` will export the `com.selesse.jxlint` package, `com.selesse.jxlint` will belong to this module no other modules can declare this package again (because a package is encapsulated in a module), otherwise a "split-package" error is returned at VM startup time.

I know module-path and Java 9 is not there yet, but I find it important to write code today that conform to the evolution of the language.

**Comment by selesse** [comment]
> I know module-path and Java 9 is not there yet, but I find it important to write code today that conform to the evolution of the language.

Cool, I didn't know this! Thanks for the info.

**Comment by jmini** [comment]
> I think any "wrapper" tool (i.e. Maven plugin, Gradle plugin, whatever) would have to convert their input into a `ProgramOptions`, like you've done in AbstractJxlintMojo#createProgramOptions. Is this still a problem? What you've done looks good to me.

The strange point with the current code (take the rules as example, but the same is also valid for categories):

* The Mojo has a `List<String>` of the rules.
* It check that the rules (or categories) are valid (code copy-pasted from `ProgramOptions#getRuleListFromOptionString(String)`) => could also be refactored. 
* Notice that at this point the Mojo could compute the `List<Rule>`.
* But for the moment the current implementation concatenates the list of rules into a single `String` value (to be stored in the `Map<JxlintOption, String>` program options)
* The `Dispatcher` convert this back into a `List<String>` and then into a `List<Rule>` 

My opinion: merge #16, because it solves #12 and it works. Then we can continue to brainstorm here and see how we could improve both contexts (CLI and Mojo).

**Comment by jmini** [comment]
In the theory, the support for command line (packages `com.selesse.jxlint` and `com.selesse.jxlint.cli` + the dependencies) could be moved to a separate project: `jxlint-cli`. What do you think?

(I could also understand that you find it convenient to let it in the `jxlint` project)

**Comment by selesse** [comment]
I'm ok with splitting it into 2 modules :)

**Comment by jmini** [comment]
You will find my proposition for the split "core" and "cli" in #21.

`jxlint-maven` now just depends from `jxlint` (core) and all the command line logic (creation of main class, parsing the command line arguments, webserver) was moved to `jxlint-cli`.

Of course downstream projects will need to depend from `jxlint-cli` if they want to provide the same possibilities as before.

**Comment by jmini** [comment]
Thank you for the merge of #21. I have discussed in this issue a point that is not fixed yet.

> The way some of the configuration are stored in `ProgramOptions` (for the list of rules or the list of categories). Here an example with the rules as example, but the same is also valid for categories:
> 
> * The Mojo has a `List<String>` of the rules.
> * It check that the rules (or categories) are valid (code copy-pasted from `ProgramOptions#getRuleListFromOptionString(String)`) => could be refactored. 
> * Notice that at this point the Mojo could compute the `List<Rule>`.
> * But for the moment the current implementation concatenates the list of rules into a single `String` value (to be stored in the `Map<JxlintOption, String>` program options)
> * The `Dispatcher` convert this back into a `List<String>` and then into a `List<Rule>`

I will try to make a proposition in to improve this, but for the moment I am not sure how to solve this.
The validation should not occur too early, but doing the validation twice (like it is the case now in the mojo use case) is not that nice.

**Comment by jmini** [comment]
#26 represents a part of the refactoring I want to do to solve this issue. 

Next step:
Store the value somewhere else as in the `Map<JxlintOption, String>` member of `ProgramOptions`.

**Comment by selesse** [comment]
Looks good, thanks for the contributions you've been making :)

**Comment by jmini** [comment]
Last step to implement the idea I have developped on this issue: #28

**Comment by jmini** [comment]
I think this issue can now be closed
