### ISSUE TITLE
Schedule for the 2.0.0 release?

### ISSUE THREAD

**Issue by jmini** [selesse/jxlint#32]
I would like to release a tool depending on the latest version of jxlint (I am using a `2.0.0-SNAPSHOT` version built locally).

Have you any schedule for a `2.0.0` release on maven central?

My alternative would be to build a `2.0.0.preview1` version and to push it on my bintray maven repository.

**Comment by selesse** [comment]
I'm OK with releasing 2.0.0. I'll get to it this week. :)

**Comment by jmini** [comment]
Version `2.0.0` is available on Maven Central:
https://mvnrepository.com/artifact/com.selesse/jxlint/2.0.0

Thank you a lot!

**Comment by jmini** [comment]
I have updated my experiments project: [jxlint-experiments](https://jmini.github.io/jxlint-experiments/). The two example linters now use version 2.0.0 of jxlint.

My tool to look for broken links and missing resources in static HTML websites is also published: https://jmini.github.io/htmlchecker/ (I will blog about this later this week).
