### ISSUE TITLE
Add support to create gradle plugins

### ISSUE THREAD

**Issue by jmini** [selesse/jxlint#38]
Similar to the `jxlint-maven` introduced with https://github.com/selesse/jxlint/issues/12, this project could host a `jxlint-gradle` that provides an abstract task `AbstractJxlintTask` (very similar to the [AbstractJxlintMojo](https://github.com/selesse/jxlint/blob/master/jxlint-maven/src/main/java/com/selesse/jxlint/maven/AbstractJxlintMojo.java)). Downstream project based on jxlint just need to extend and configure the task.

I have started such a class here: [AbstractJxlintTask](https://github.com/jmini/htmlchecker/blob/wip-gradle/htmlchecker-gradle-plugin/src/main/java/com/selesse/jxlint/gradle/AbstractJxlintTask.java).

---

1) are you interested by this contribution?

2) I have used [`@Option`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/options/Option.html) which was introduced with gradle 4.6. Is it possible to update the gradle version used in this project (currently 4.1 defined with the wrapper)? What is your preferred version? We can stay on the 4.x stream if this is a requirement.

**Comment by selesse** [comment]
I like this idea, it was something that I wanted to explore at some point. Feel free to change the Gradle version to whatever you need (the latest released version would be fine) - I have no requirements at all. :)

**Comment by selesse** [comment]
Thanks! Do you want a 2.2.0 release for this or did you want to add anything else?

**Comment by jmini** [comment]
Sorry for the late reply.

No for the moment I do not plan to add anything else. A release would be great!

**Comment by selesse** [comment]
I created the release this morning: [tag](https://github.com/selesse/jxlint/releases/tag/2.2.0) and  [Maven Central](https://repo.maven.apache.org/maven2/com/selesse/jxlint/2.2.0/).
